<script>
    if ( (typeof jQuery === 'undefined') && !window.jQuery && (typeof isPrcJsLoaded === 'undefined')) {
        isPrcJsLoaded = true;
        var head = document.getElementsByTagName('head')[0];
        var script = document.createElement('script');
        script.type = 'text/javascript';
        script.src  = '<?php echo $this->getJsPath() ?>/jquery-311.min.js';

        if(script.readyState) {  //IE
            script.onreadystatechange = function() {
                if ( script.readyState === "loaded" || script.readyState === "complete" ) {
                    script.onreadystatechange = null;
                    callback();
                    loadPrcJs();
                }
            };
        } else {  //Others
            script.onload = function() {
                loadPrcJs();
            };
        }

        head.appendChild(script);
    } else {
        if((typeof jQuery === 'undefined') && window.jQuery) {
            jQuery = window.jQuery;
        } else if((typeof jQuery !== 'undefined') && !window.jQuery) {
            window.jQuery = jQuery;
        }
    }

    function loadPrcJs(){
        $ = jQuery.noConflict(true);

        var head = document.getElementsByTagName('head')[0];
        var script = document.createElement('script');
        script.type = 'text/javascript';
        script.src  = '<?php echo $this->getJsPath() ?>/ekomi-prc.js';
        head.appendChild(script);
    }
</script>
<?php if ($this->isModuleEnabled()) { ?>
    <?php $productId = $this->getCurrentProduct()->getId() ?>
    <?php $totalProductReviewCount = $this->getProductReviewsCount(); ?>
    <?php if ($totalProductReviewCount > 0) { ?>
        <!-- product average rating  -->
        <div class="ekomi_average_rating">
            <div class="ekomi_average_stars">
                <div class="ekomi_stars_wrap">
                    <div class="ekomi_stars_gold" style="width:<?= ($this->getMiniStarsAvg() * 20); ?>%"></div>
                </div>
            </div>
        </div>
    <?php } ?>
<?php } ?>